# Staging environment configuration overrides

server:
  port: 8080

database:
  host: staging-db.example.com
  port: 5432
  name: mini_ewallet_staging
  user: staging_user
  password: ${DB_PASSWORD}
  max_open_conns: 50
  max_idle_conns: 50

redis:
  addr: staging-redis.example.com:6379
  password: ${REDIS_PASSWORD}

kafka:
  brokers:
    - staging-kafka-1.example.com:9092
    - staging-kafka-2.example.com:9092
    - staging-kafka-3.example.com:9092

payment:
  midtrans:
    server_key: ${MIDTRANS_SERVER_KEY}
    client_key: ${MIDTRANS_CLIENT_KEY}
    is_production: false
  stripe:
    api_key: ${STRIPE_API_KEY}
    webhook_secret: ${STRIPE_WEBHOOK_SECRET}
    is_test: true

logging:
  level: info